name: Doc Test

on:
  push:
    paths:
      - '"docs/**/*"'
  pull_request:
    paths:
      - '"docs/**/*"'
  workflow_dispatch:

jobs:
    e2e-test:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: 9
                run_install: false

            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: lts/*

            - name: Install dependencies
              run: pnpm install
              working-directory: ./docs

            - name: Install playwright dependencies
              run: npx playwright install --with-deps
              working-directory: ./docs

            - name: Run E2E tests
              run: npm run e2e
              working-directory: ./docs