name: App Test

on:
  push:
    paths-ignore:
      - '"**/*.md"'
      - '"**/*.mdx"'
      - '.vscode/**'
      - 'coverage/**'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '"**/*.md"'
      - '"**/*.mdx"'
      - '.vscode/**'
      - 'coverage/**'
      - 'docs/**'
  workflow_dispatch:

jobs:
    cargo-test:
        timeout-minutes: 10
        # ignore if commit message contains chore or ci
        if: ${{ !contains(github.event.head_commit.message, 'ci') && !contains(github.event.head_commit.message, 'chore') }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: install dependencies (ubuntu only)
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
                # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
                # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

            - name: Setup Rust
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                workspaces: './src-tauri -> target'

            - name: Install dependencies
              run: cargo build --verbose
              working-directory: ./src-tauri/

            - name: Run tests
              run: cargo test --verbose
              working-directory: ./src-tauri/

    npm-test:
        timeout-minutes: 10
        # ignore if commit message contains chore or ci
        if: ${{ !contains(github.event.head_commit.message, 'ci') && !contains(github.event.head_commit.message, 'chore') }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                node-version: lts/*
                cache: 'npm' # Set this to npm, yarn or pnpm.

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test